AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
  LineBot-FunFeatures

Parameters:
  LineUserID:
    NoEcho: true
    Type: String
  CelebratingTarget:
    NoEcho: true
    Type: String
  LineBotSecret:
    NoEcho: true
    Type: String
  LineBotAccessToken:
    NoEcho: true
    Type: String

Resources:
  ResponseForPostRequests:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: ./src
      Handler: app.main.response
      Runtime: python3.7
      Environment:
        Variables:
          LINE_USER_ID:
            Ref: LineUserID
          CELEBRATING_TARGET:
            Ref: CelebratingTarget
          LINEBOT_SECRET:
            Ref: LineBotSecret
          LINEBOT_ACCESS_TOKEN:
            Ref: LineBotAccessToken
      Policies: AmazonDynamoDBFullAccess
      Timeout: 30
      Events:
        PutRequest:
          Type: Api
          Properties:
            Path: /callback/
            Method: post
